dist: bionic

os: linux

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  jobs:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""
    - SSL_TEST="yes" SSL_CA="ssl/ca.pem" SSL_PEER_NAME="server.rmq"
    - SSL_TEST="yes" SSL_CA="ssl/ca.pem" SSL_PEER_NAME="server.rmq" SSL_CLIENT_CERT="ssl/client.pem" SSL_CLIENT_KEY="ssl/client.key"

jobs:
  allow_failures:
    - php: nightly

install:
  - composer update --prefer-source $PREFER_LOWEST

before_script:
  - if [ ! -z "$SSL_TEST" ] ; then test/ssl/travis.sh; fi
  - sudo rabbitmqctl add_vhost testvhost
  - sudo rabbitmqctl add_user testuser testpassword
  - sudo rabbitmqctl set_permissions -p testvhost testuser ".*" ".*" ".*"

script:
  - TEST_RABBITMQ_CONNECTION_URI=amqp://testuser:testpassword@localhost:5672/testvhost ./vendor/bin/phpunit

services:
  - rabbitmq

addons:
  apt:
    packages:
      - rabbitmq-server
